spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 12345678
  jpa:
    show-sql: true

app:
  page-size: 10

stripe:
  apiUrl: https://api.stripe.com
  enable: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP

payment-gateway: strip

mail:
  host: https://smtp.gmail.com
  port: 8000

